- name: Setup webservers
  hosts: all
  become: true
  tags: [setup]

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - role: geerlingguy.docker
      when: install_docker | default(false)

- name: Deploy Redmine application
  hosts: all
  become: true
  tags: [deploy]

  tasks:
    - name: Create .env file from template
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: /root/redmine.env
        mode: '0600'

    - name: Allow Redmine traffic through firewall
      community.general.ufw:
        rule: allow
        port: "{{ redmine_port }}"
        proto: tcp
      when: inventory_hostname != 'localhost'

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        state: started
        restart_policy: always
        ports:
          - "{{ redmine_port }}:3000"
        env_file: /root/redmine.env

- name: Setup monitoring
  hosts: webservers
  become: true
  tags: [monitoring]

  roles:
    - role: datadog.dd.agent
