# DB config
db_host: "db-postgresql-sgp1-93083-do-user-8866883-0.m.db.ondigitalocean.com"
db_port: 25060
db_name: "defaultdb"
db_user: "doadmin"
db_password: "{{ vault_db_password }}"

# DataDog config
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: "datadoghq.eu"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Redmine Health Check
        url: "http://localhost:{{ redmine_port }}"
        timeout: 5
